server.port=5001

# PostgreSQL connection
spring.datasource.url=jdbc:postgresql://localhost:5432/fyp_db
spring.datasource.username=postgres
spring.datasource.password=Mitrran@27
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Error details
server.error.include-exception=true
server.error.include-stacktrace=always

# File upload limits
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB